name: Manga Bot Auto Run

on:
  schedule:
    # Run every 20 minutes
    - cron: '*/20 * * * *'
  workflow_dispatch: # Allow manual trigger

jobs:
  run-manga-bot:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Create sensitive config files from secrets
      run: |
        echo '${{ secrets.SETTINGS_JSON }}' > settings.json
        echo '${{ secrets.CREDENTIALS_JSON }}' > credentials.json
        echo '${{ secrets.TOKEN_JSON }}' > token.json
    
    - name: Setup state repository
      run: |
        # Clone the state repository
        git clone https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository_owner }}/manga-bot-state.git state-repo
        
        # Copy existing state.json if it exists
        if [ -f "state-repo/state.json" ]; then
          cp state-repo/state.json .
        else
          echo '{}' > state.json
        fi
    
    - name: Run manga bot
      run: python bot.py
    
    - name: Update state repository
      if: always()
      run: |
        # Copy updated state.json to state repository
        cp state.json state-repo/
        
        # Push changes to state repository
        cd state-repo
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add state.json
        
        # Only commit if there are changes
        if ! git diff --staged --quiet; then
          git commit -m "Update processing state - $(date)"
          git push origin main
        else
          echo "No changes to state.json"
        fi
      
    - name: Upload logs
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: manga-bot-logs
        path: manga_bot.log
        retention-days: 7