name: Manga Bot Auto Run

on:
  schedule:
    # Run every 20 minutes
    - cron: '*/20 * * * *'
  workflow_dispatch: # Allow manual trigger

jobs:
  run-manga-bot:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Create config files from secrets
      run: |
        echo '${{ secrets.CONFIG_JSON }}' > config.json
        echo '${{ secrets.SETTINGS_JSON }}' > settings.json
        echo '${{ secrets.CREDENTIALS_JSON }}' > credentials.json
        echo '${{ secrets.SERVICE_ACCOUNT_JSON }}' > service-account.json
        echo '${{ secrets.STATE_JSON }}' > state.json
    
    - name: Run manga bot
      run: python bot.py
    
    - name: Update state file
      run: |
        # Read the updated state.json and save it back to secrets
        if [ -f state.json ]; then
          echo "State file exists, updating..."
          # Note: GitHub Actions can't update secrets automatically
          # You'll need to manually update the STATE_JSON secret periodically
          # or use a different approach like storing state in a separate repository
        fi
    
    - name: Upload logs as artifact
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: manga-bot-logs
        path: manga_bot.log
        retention-days: 7
