name: Manga Bot Auto Run

on:
  schedule:
    # Run every 20 minutes
    - cron: '*/20 * * * *'
  workflow_dispatch: # Allow manual trigger

jobs:
  run-manga-bot:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Create sensitive config files from secrets
      run: |
        echo '${{ secrets.SETTINGS_JSON }}' > settings.json
        echo '${{ secrets.CREDENTIALS_JSON }}' > credentials.json
        echo '${{ secrets.TOKEN_JSON }}' > token.json
    
    - name: Clone or create state repository
      run: |
        git clone https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository_owner }}/manga-bot-state.git state-repo 2>/dev/null || {
          mkdir state-repo
          cd state-repo
          git init
          git remote add origin https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository_owner }}/manga-bot-state.git
          echo '{}' > state.json
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add state.json
          git commit -m "Initialize state repository"
          git push -u origin main 2>/dev/null || git push -u origin master 2>/dev/null || echo "Repository might already exist"
        }
        cp state-repo/state.json . 2>/dev/null || echo '{}' > state.json
    
    - name: Run manga bot
      run: python bot.py
    
    - name: Update state repository
      if: always()
      run: |
        cp state.json state-repo/ 2>/dev/null || echo "No state file to update"
        cd state-repo
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add state.json
        git diff --staged --quiet || {
          git commit -m "Update processing state - $(date)"
          git push
        }
      
    - name: Upload logs
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: manga-bot-logs
        path: manga_bot.log
        retention-days: 7